name: CD - Deploy React Native App with Expo EAS

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    strategy:
      matrix:
        platform: [android, ios]
    runs-on: ${{ matrix.platform == 'ios' && 'macos-latest' || 'ubuntu-latest' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install dependencies
        run: npm install

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}  # Required for authentication

      - name: Build
        run: |
          eas build --platform ${{ matrix.platform }} --profile production --non-interactive

      - name: Get Build URL
        run: |
          echo "Internal build URL available in Expo dashboard"